/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Receipt } from './receipt';
import { ReportStatus } from './reportStatus';


/**
 * A named, group-scoped collection of receipts for an expense claim
 */
export interface Report { 
    createdAt?: string;
    createdBy?: number;
    id: number;
    /**
     * Name of the report
     */
    name: string;
    /**
     * Group foreign key
     */
    groupId: number;
    /**
     * Report lifecycle status
     */
    status: ReportStatus;
    /**
     * When the report was marked submitted
     */
    submittedDate?: string;
    /**
     * When the report was marked paid
     */
    paidDate?: string;
    /**
     * Receipts assigned to the report
     */
    receipts?: Array<Receipt>;
    updatedAt?: string;
}
export namespace Report {
}


