/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of an expense report
 */
export type ReportStatus = 'DRAFT' | 'SUBMITTED' | 'PAID' | '';

export const ReportStatus = {
    Draft: 'DRAFT' as ReportStatus,
    Submitted: 'SUBMITTED' as ReportStatus,
    Paid: 'PAID' as ReportStatus,
    Empty: '' as ReportStatus
};

