/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupTaxRule } from './groupTaxRule';


export interface UpdateGroupReceiptSettingsCommand { 
    /**
     * Hide receipt images
     */
    hideImages?: boolean;
    /**
     * Hide receipt categories
     */
    hideReceiptCategories?: boolean;
    /**
     * Hide receipt tags
     */
    hideReceiptTags?: boolean;
    /**
     * Hide receipt item categories
     */
    hideItemCategories?: boolean;
    /**
     * Hide receipt item tags
     */
    hideItemTags?: boolean;
    /**
     * Hide receipt comments
     */
    hideComments?: boolean;
    /**
     * Hide share categories
     */
    hideShareCategories?: boolean;
    /**
     * Hide share tags
     */
    hideShareTags?: boolean;
    /**
     * Home currency (ISO 4217) for expense reports
     */
    homeCurrency?: string;
    /**
     * Prefer the receipt\'s printed tax over a computed rate
     */
    usePrintedTax?: boolean;
    /**
     * Fallback tax rate used when no printed tax is available
     */
    defaultTaxRate?: number;
    /**
     * Per-country tax treatment rules
     */
    taxRules?: Array<GroupTaxRule>;
}

