/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportStatus } from './reportStatus';


export interface UpsertReportCommand { 
    /**
     * Report name
     */
    name: string;
    /**
     * Group foreign key
     */
    groupId: number;
    /**
     * Optional status to set
     */
    status?: ReportStatus;
}
export namespace UpsertReportCommand {
}


